export const RANDOM_MEAL: string = "https://www.themealdb.com/api/json/v1/1/random.php"
export const CATEGORIES: string = "https://www.themealdb.com/api/json/v1/1/categories.php"
export const FILTER_BY_CATEGORIES: string = "https://www.themealdb.com/api/json/v1/1/filter.php?c="
export const MAIN_INGREDIENT: string = "https://www.themealdb.com/api/json/v1/1/filter.php?i="
export const LIST_INGREDIENT: string = "https://www.themealdb.com/api/json/v1/1/list.php?i=list"
export const LIST_CATEGORIES: string = "https://www.themealdb.com/api/json/v1/1/list.php?c=list"
export const LIST_AREA: string = "https://www.themealdb.com/api/json/v1/1/list.php?a=list"